manager/urls.py
from django.urls import path

from manager.views import (
    index,
    WorkersListView,
    TasksListView,
    TasksCreateView,
    TaskDetailView,
    TaskDeleteView,
    TaskUpdateView,
    MyTaskListView,
    WorkersDetailView,
    WorkersCreateView,
    WorkersUpdateView,
    WorkersDeleteView,
)

urlpatterns =  [
    path("", index, name="index"),
    path("workers/", WorkersListView.as_view(), name="workers-list"),
    path("tasks/", TasksListView.as_view(), name="tasks-list"),
    path("tasks/create/", TasksCreateView.as_view(), name="tasks-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="tasks-detail"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="tasks-delete"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="tasks-update"),
    path("mytasks/<int:pk>", MyTaskListView.as_view(), name="mytasks-list"),
    path("workers/<int:pk>/", WorkersDetailView.as_view(), name="workers-detail"),
    path("workers/create", WorkersCreateView.as_view(), name="workers-create"),
    path("workers/<int:pk>/update/", WorkersUpdateView.as_view(), name="workers-update"),
    path("workers/<int:pk>/delete/", WorkersDeleteView.as_view(), name="workers-delete"),

]
app_name = "manager"

manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from task_manager import settings


class TaskType(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    class StrChoices(models.TextChoices):
        URGENT = "1", "Urgent"
        HIGH = "2", "High"
        MEDIUM = "3", "Medium"
        LOW = "4", "Low"

    name = models.CharField(max_length=63)
    description = models.TextField(blank=True)
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=3,
        choices=StrChoices.choices,
        default=StrChoices.MEDIUM,
    )
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(settings.base.AUTH_USER_MODEL, related_name="tasks")

    class Meta:
        ordering = ["is_completed", "priority"]

    def __str__(self):
        return f"Name: {self.name}, type: {self.task_type.name}, priority: {self.priority}"

class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.DO_NOTHING,
        null=True,
    )
    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.username}: {self.first_name} {self.last_name}"

manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import CheckboxInput

from manager.models import Worker, Task


class WorkerCreationForm(UserCreationForm):
    class Meta:
        model = Worker
        fields = UserCreationForm.Meta.fields + ("position", )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "custom-class"


class WorkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ("first_name", "last_name", "email", "position",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "custom-class"


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )
    class Meta:
        model = Task
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            if not isinstance(field.widget, CheckboxInput):
                field.widget.attrs["class"] = "custom-class"


class TaskSearchForm(forms.Form):
    parameter = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Search by name, type"
            }
        )
    )



class WorkerSearchForm(forms.Form):
    parameter = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Search by username, first/last name, position"
            }
        )
    )

manager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import WorkerCreationForm, WorkerUpdateForm, TaskForm, TaskSearchForm, WorkerSearchForm
# from .forms import TaskForm
from .models import Worker, Task

def index(request) -> HttpResponse:
    num_workers = get_user_model().objects.count()
    num_active_tasks = Task.objects.filter(is_completed=False).count()
    num_completed_tasks = Task.objects.filter(is_completed=True).count()
    context = {
        "num_workers": num_workers,
        "num_active_tasks": num_active_tasks,
        "num_completed_tasks": num_completed_tasks,
    }
    return render(request, "manager/index.html", context)


class WorkersListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5
    queryset = Worker.objects.all().select_related("position")

    def get_context_data(
            self, *, object_list=..., **kwargs
    ):
        context = super(WorkersListView, self).get_context_data(**kwargs)
        parameter = self.request.GET.get("parameter", "")
        context["search_form"] = WorkerSearchForm(initial={"parameter": parameter})
        return context

    def get_queryset(self):
        param = self.request.GET.get("parameter")
        if param:
            return self.queryset.filter(
                Q(username__icontains=param) |
                Q(first_name__icontains=param) |
                Q(last_name__icontains=param) |
                Q(position__name__icontains=param))
        return self.queryset.all()


class TasksListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5
    queryset = Task.objects.select_related("task_type")

    def get_context_data(
            self, *, object_list=..., **kwargs
    ):
        context = super(TasksListView, self).get_context_data(**kwargs)
        parameter = self.request.GET.get("parameter", "")
        context["search_form"] = TaskSearchForm(initial={"parameter": parameter})
        context["page_name"] = "Task list"
        return context

    def get_queryset(self):
        param = self.request.GET.get("parameter")
        if param:
            return self.queryset.filter(
                Q(name__icontains=param) |
                Q(task_type__name__icontains=param))
        return self.queryset.all()


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TasksCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:tasks-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("manager:tasks-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:tasks-list")


class MyTaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 10
    template_name = "manager/task_list.html"

    def get_context_data(
            self, *, object_list=..., **kwargs
    ):
        context = super(MyTaskListView, self).get_context_data(**kwargs)
        parameter = self.request.GET.get("parameter", "")
        context["search_form"] = TaskSearchForm(initial={"parameter": parameter})
        context["page_name"] = "My tasks"
        return context

    def get_queryset(self):
        queryset =  Task.objects.filter(id=self.kwargs["pk"]).select_related("task_type")
        param = self.request.GET.get("parameter")
        if param:
            return queryset.filter(
                Q(name__icontains=param) |
                Q(task_type__name__icontains=param))
        return queryset.all()




class WorkersDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = get_user_model().objects.all().select_related("position").prefetch_related("tasks__task_type")


class WorkersCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("manager:workers-list")


class WorkersUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("manager:workers-list")


class WorkersDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("manager:workers-list")

templates/manager/task_confirm_delete.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Task list {% endblock %}

{#{% block body_class %} about-us {% endblock %}#}

<!-- Specific Page CSS goes HERE  -->
{#{% block stylesheets %}{% endblock stylesheets %}#}

{% block content %}

  {% include 'includes/navigation.html' %}
  <header class="bg-gradient-dark">
    <div class="page-header min-vh-35" style="background-image: url('{{ ASSETS_ROOT }}/img/bg9.jpg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">
              {{ task.name }}
            </h1>
          </div>
        </div>
      </div>
    </div>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
  <!-- Section with four info areas left & one card right with image and waves -->
  <section class="py-7">
    <div class="container">
      <div class="row align-items-center text-center">
        <h1>Do you want to delete this task?</h1>
        <form method="post" action="">
          {% csrf_token %}
          <br>
          <input class="btn btn-danger" type="submit" value="Yes, I do">
          <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
    </div>
  </section>
  <!-- END Section with four info areas left & one card right with image and waves -->


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
      // get the element to animate
      var element = document.getElementById('count-stats');
      var elementHeight = element.clientHeight;

      // listen for scroll event and call animate function

      document.addEventListener('scroll', animate);

      // check if element is in view
      function inView() {
          // get window height
          var windowHeight = window.innerHeight;
          // get number of pixels that the document is scrolled
          var scrollY = window.scrollY || window.pageYOffset;
          // get current scroll position (distance from the top of the page to the bottom of the current viewport)
          var scrollPosition = scrollY + windowHeight;
          // get element position (distance from the top of the page to the bottom of the element)
          var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

          // is scroll position greater than element position? (is element in view?)
          if (scrollPosition > elementPosition) {
              return true;
          }

          return false;
      }

      var animateComplete = true;

      // animate element when it is in view
      function animate() {

          // is element in view?
          if (inView()) {
              if (animateComplete) {
                  if (document.getElementById('state1')) {
                      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
                      if (!countUp.error) {
                          countUp.start();
                      } else {
                          console.error(countUp.error);
                      }
                  }
                  if (document.getElementById('state2')) {
                      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
                      if (!countUp1.error) {
                          countUp1.start();
                      } else {
                          console.error(countUp1.error);
                      }
                  }
                  if (document.getElementById('state3')) {
                      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
                      if (!countUp2.error) {
                          countUp2.start();
                      } else {
                          console.error(countUp2.error);
                      }
                      ;
                  }
                  animateComplete = false;
              }
          }
      }

      if (document.getElementById('typed')) {
          var typed = new Typed("#typed", {
              stringsElement: '#typed-strings',
              typeSpeed: 90,
              backSpeed: 90,
              backDelay: 200,
              startDelay: 500,
              loop: true
          });
      }
  </script>

  <script>
      if (document.getElementsByClassName('page-header')) {
          window.onscroll = debounce(function () {
              var scrollPosition = window.pageYOffset;
              var bgParallax = document.querySelector('.page-header');
              var oVal = (window.scrollY / 3);
              bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
          }, 6);
      }
  </script>

{% endblock javascripts %}

templates/manager/task_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Task list {% endblock %}

{#{% block body_class %} about-us {% endblock %}#}

<!-- Specific Page CSS goes HERE  -->
{#{% block stylesheets %}{% endblock stylesheets %}#}

{% block content %}

  {% include 'includes/navigation.html' %}
  <header class="bg-gradient-dark">
    <div class="page-header min-vh-35" style="background-image: url('{{ ASSETS_ROOT }}/img/bg9.jpg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">
              {{ task.name }}
            </h1>
          </div>
        </div>
      </div>
    </div>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
  <!-- Section with four info areas left & one card right with image and waves -->
  <section class="py-7">
    <div class="container">
      <div class="row align-items-center">
        <h1>Task №{{ task.id }}
          <a href="{% url 'manager:tasks-delete' pk=task.id %}" class="btn btn-danger link-to-page">
            Delete
          </a>

          <a href="{% url 'manager:tasks-update' pk=task.id %}" class="btn btn-secondary link-to-page">
            Update
          </a>
        </h1>
        <p>Name: {{ task.name }}</p>
        <p>Priority: {% if task.priority == "1" %}Urgent
        {% endif %}
          {% if task.priority == "2" %}High
          {% endif %}
          {% if task.priority == "3" %}Medium
          {% endif %}
          {% if task.priority == "4" %}Low
          {% endif %}</p>
        <p>Deadline: {{ task.deadline }}</p>
        <p>Completed: {% if task.is_completed is False %}No{% else %}Yes{% endif %}</p>
        <p>Type: {{ task.task_type.name }}</p>
        <p>Assignees:
        <ul>
          {% for worker in task.assignees.all %}
            <li><a href="{% url 'manager:workers-detail' pk=worker.id %}">{{ worker.username }}</a>
              - {{ worker.first_name }} {{ worker.last_name }}</li>
          {% endfor %}
        </ul>
        </p>
        <p>Description: {{ task.description }}</p>
      </div>
    </div>
  </section>
  <!-- END Section with four info areas left & one card right with image and waves -->


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
      // get the element to animate
      var element = document.getElementById('count-stats');
      var elementHeight = element.clientHeight;

      // listen for scroll event and call animate function

      document.addEventListener('scroll', animate);

      // check if element is in view
      function inView() {
          // get window height
          var windowHeight = window.innerHeight;
          // get number of pixels that the document is scrolled
          var scrollY = window.scrollY || window.pageYOffset;
          // get current scroll position (distance from the top of the page to the bottom of the current viewport)
          var scrollPosition = scrollY + windowHeight;
          // get element position (distance from the top of the page to the bottom of the element)
          var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

          // is scroll position greater than element position? (is element in view?)
          if (scrollPosition > elementPosition) {
              return true;
          }

          return false;
      }

      var animateComplete = true;

      // animate element when it is in view
      function animate() {

          // is element in view?
          if (inView()) {
              if (animateComplete) {
                  if (document.getElementById('state1')) {
                      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
                      if (!countUp.error) {
                          countUp.start();
                      } else {
                          console.error(countUp.error);
                      }
                  }
                  if (document.getElementById('state2')) {
                      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
                      if (!countUp1.error) {
                          countUp1.start();
                      } else {
                          console.error(countUp1.error);
                      }
                  }
                  if (document.getElementById('state3')) {
                      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
                      if (!countUp2.error) {
                          countUp2.start();
                      } else {
                          console.error(countUp2.error);
                      }
                      ;
                  }
                  animateComplete = false;
              }
          }
      }

      if (document.getElementById('typed')) {
          var typed = new Typed("#typed", {
              stringsElement: '#typed-strings',
              typeSpeed: 90,
              backSpeed: 90,
              backDelay: 200,
              startDelay: 500,
              loop: true
          });
      }
  </script>

  <script>
      if (document.getElementsByClassName('page-header')) {
          window.onscroll = debounce(function () {
              var scrollPosition = window.pageYOffset;
              var bgParallax = document.querySelector('.page-header');
              var oVal = (window.scrollY / 3);
              bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
          }, 6);
      }
  </script>

{% endblock javascripts %}

templates/manager/task_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Task list {% endblock %}

{#{% block body_class %} about-us {% endblock %}#}

<!-- Specific Page CSS goes HERE  -->
{#{% block stylesheets %}{% endblock stylesheets %}#}

{% block content %}

  {% include 'includes/navigation.html' %}
  <header class="bg-gradient-dark">
    <div class="page-header min-vh-35" style="background-image: url('{{ ASSETS_ROOT }}/img/bg9.jpg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">
              {{ page_name }}
            </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <!-- Section with four info areas left & one card right with image and waves -->
    <section class="py-7">
      <div class="container">
        <div class="row align-items-center">
            <h1>{{ page_name }}
              <a href="{% url 'manager:tasks-create' %}" class="btn btn-primary link-to-page">
                Create
              </a>
            </h1>

            <br>
            <form action="" method="get">
              {{ search_form|crispy }}
              <input class="btn btn-primary" type="submit" value="Search">
            </form>
            <br>

            {% if task_list %}
              <table class="table">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Deadline</th>
                  <th>Completed</th>
                  <th>Priority</th>
                  <th>Type</th>
                </tr>
                {% for task in task_list %}
                  <tr>
                    <td>{{ task.id }}</td>
                    <td><a href="{% url 'manager:tasks-detail' pk=task.id %}">{{ task.name }}</a></td>
                    <td>{{ task.deadline }}</td>
                    <td>{% if task.is_completed is False %}No{% else %}Yes{% endif %}</td>
                    <td>{% if task.priority == "1" %}Urgent
                    {% endif %}
                      {% if task.priority == "2" %}High
                      {% endif %}
                      {% if task.priority == "3" %}Medium
                      {% endif %}
                      {% if task.priority == "4" %}Low
                      {% endif %}
                    </td>
                    <td>{{ task.task_type.name }}</td>
                  </tr>
                {% endfor %}
                {% else %}
                <p>There are no one task</p>
              </table>
            {% endif %}
        </div>
      </div>
    </section>
    <!-- END Section with four info areas left & one card right with image and waves -->


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    // get the element to animate
    var element = document.getElementById('count-stats');
    var elementHeight = element.clientHeight;

    // listen for scroll event and call animate function

    document.addEventListener('scroll', animate);

    // check if element is in view
    function inView() {
      // get window height
      var windowHeight = window.innerHeight;
      // get number of pixels that the document is scrolled
      var scrollY = window.scrollY || window.pageYOffset;
      // get current scroll position (distance from the top of the page to the bottom of the current viewport)
      var scrollPosition = scrollY + windowHeight;
      // get element position (distance from the top of the page to the bottom of the element)
      var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

      // is scroll position greater than element position? (is element in view?)
      if (scrollPosition > elementPosition) {
        return true;
      }

      return false;
    }

    var animateComplete = true;
    // animate element when it is in view
    function animate() {

      // is element in view?
      if (inView()) {
        if (animateComplete) {
          if (document.getElementById('state1')) {
            const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
            if (!countUp.error) {
              countUp.start();
            } else {
              console.error(countUp.error);
            }
          }
          if (document.getElementById('state2')) {
            const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
            if (!countUp1.error) {
              countUp1.start();
            } else {
              console.error(countUp1.error);
            }
          }
          if (document.getElementById('state3')) {
            const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
            if (!countUp2.error) {
              countUp2.start();
            } else {
              console.error(countUp2.error);
            };
          }
          animateComplete = false;
        }
      }
    }

    if (document.getElementById('typed')) {
      var typed = new Typed("#typed", {
        stringsElement: '#typed-strings',
        typeSpeed: 90,
        backSpeed: 90,
        backDelay: 200,
        startDelay: 500,
        loop: true
      });
    }
  </script>

  <script>
    if (document.getElementsByClassName('page-header')) {
      window.onscroll = debounce(function() {
        var scrollPosition = window.pageYOffset;
        var bgParallax = document.querySelector('.page-header');
        var oVal = (window.scrollY / 3);
        bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
      }, 6);
    }
  </script>

{% endblock javascripts %}

templates/manager/worker_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Task list {% endblock %}

{#{% block body_class %} about-us {% endblock %}#}

<!-- Specific Page CSS goes HERE  -->
{#{% block stylesheets %}{% endblock stylesheets %}#}

{% block content %}

  {% include 'includes/navigation.html' %}
  <header class="bg-gradient-dark">
    <div class="page-header min-vh-35" style="background-image: url('{{ ASSETS_ROOT }}/img/bg9.jpg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">
              {% if worker.id == user.id %}
              My page
              {% else %}
              {{ worker.username }}
              {% endif %}
            </h1>
          </div>
        </div>
      </div>
    </div>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
  <!-- Section with four info areas left & one card right with image and waves -->
  <section class="py-7">
    <div class="container">
      <div class="row align-items-center">
        <h1>{{ worker.username }}
          <a href="{% url 'manager:workers-delete' pk=worker.id %}" class="btn btn-danger link-to-page">
            Delete
          </a>

          <a href="{% url 'manager:workers-update' pk=worker.id %}" class="btn btn-secondary link-to-page">
            Update
          </a>
        </h1>
        <p>First name: {{ worker.first_name }}</p>
        <p>Last name: {{ worker.last_name }}</p>
        <p>Position: {{ worker.position }}</p>
        <p>Tasks:
        <ul>
          {% for task in worker.tasks.all %}
            <li><a href="{% url 'manager:tasks-detail' pk=task.id %}">{{ task.name }}
              - {{ task.deadline }} {{ task.task_type.name }}</a></li>
          {% endfor %}
        </ul>
        </p>
      </div>
    </div>
  </section>
  <!-- END Section with four info areas left & one card right with image and waves -->


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
      // get the element to animate
      var element = document.getElementById('count-stats');
      var elementHeight = element.clientHeight;

      // listen for scroll event and call animate function

      document.addEventListener('scroll', animate);

      // check if element is in view
      function inView() {
          // get window height
          var windowHeight = window.innerHeight;
          // get number of pixels that the document is scrolled
          var scrollY = window.scrollY || window.pageYOffset;
          // get current scroll position (distance from the top of the page to the bottom of the current viewport)
          var scrollPosition = scrollY + windowHeight;
          // get element position (distance from the top of the page to the bottom of the element)
          var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

          // is scroll position greater than element position? (is element in view?)
          if (scrollPosition > elementPosition) {
              return true;
          }

          return false;
      }

      var animateComplete = true;

      // animate element when it is in view
      function animate() {

          // is element in view?
          if (inView()) {
              if (animateComplete) {
                  if (document.getElementById('state1')) {
                      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
                      if (!countUp.error) {
                          countUp.start();
                      } else {
                          console.error(countUp.error);
                      }
                  }
                  if (document.getElementById('state2')) {
                      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
                      if (!countUp1.error) {
                          countUp1.start();
                      } else {
                          console.error(countUp1.error);
                      }
                  }
                  if (document.getElementById('state3')) {
                      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
                      if (!countUp2.error) {
                          countUp2.start();
                      } else {
                          console.error(countUp2.error);
                      }
                      ;
                  }
                  animateComplete = false;
              }
          }
      }

      if (document.getElementById('typed')) {
          var typed = new Typed("#typed", {
              stringsElement: '#typed-strings',
              typeSpeed: 90,
              backSpeed: 90,
              backDelay: 200,
              startDelay: 500,
              loop: true
          });
      }
  </script>

  <script>
      if (document.getElementsByClassName('page-header')) {
          window.onscroll = debounce(function () {
              var scrollPosition = window.pageYOffset;
              var bgParallax = document.querySelector('.page-header');
              var oVal = (window.scrollY / 3);
              bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
          }, 6);
      }
  </script>

{% endblock javascripts %}