manager/urls.py
from django.urls import path

from manager.views import (
    index,
    WorkersListView,
    TasksListView,
    TasksCreateView,
    TaskDetailView,
    TaskDeleteView,
    TaskUpdateView,
    MyTaskListView,
    WorkersDetailView,
    WorkersCreateView,
    WorkersUpdateView,
    WorkersDeleteView,
)

urlpatterns =  [
    path("", index, name="index"),
    path("workers/", WorkersListView.as_view(), name="workers-list"),
    path("tasks/", TasksListView.as_view(), name="tasks-list"),
    path("tasks/create/", TasksCreateView.as_view(), name="tasks-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="tasks-detail"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="tasks-delete"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="tasks-update"),
    path("mytasks/<int:pk>", MyTaskListView.as_view(), name="mytasks-list"),
    path("workers/<int:pk>/", WorkersDetailView.as_view(), name="workers-detail"),
    path("workers/create", WorkersCreateView.as_view(), name="workers-create"),
    path("workers/<int:pk>/update/", WorkersUpdateView.as_view(), name="workers-update"),
    path("workers/<int:pk>/delete/", WorkersDeleteView.as_view(), name="workers-delete"),

]
app_name = "manager"

templates/includes/navigation.html
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip"
             title="Back to Home page" data-placement="bottom">
            Task Manager
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                   title="My tasks" href="{% url 'manager:mytasks-list' pk=user.id %}">
                  My tasks
                </a>
              </li>
            {% endif %}
              <li class="nav-item">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                   title="All tasks" href="{% url 'manager:tasks-list' %}">
                  All tasks
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                   title="All workers" href="{% url 'manager:workers-list' %}">
                  All workers
                </a>
              </li>


              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'manager:workers-detail' pk=user.id %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom" title="My page">{{ user.username }}</p>
                  </a>
                </li>
                <li class="nav-item ms-lg-auto">
                  <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                         data-bs-placement="bottom" title="Logout">Logout</p>
                    </button>
                  </form>
                </li>
              {% else %}
                <li class="nav-item ms-lg-auto">
                  <a class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0"
                     href="{% url 'login' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom" title="Login">Login</p>
                  </a>
                </li>

              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">&lt;</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">&gt;</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>